### ISSUE TITLE
[Bug]: Install error

### ISSUE THREAD

**Issue by MasyGreen** [AlexeyLCP/lucx-ui#114]
### Describe the bug

Установка завершилась ошибкой +  x-ui install-awg дает ту же ошибку

### How to reproduce the problem

Запуск через основной установщик на абсолютно чистой системе поле apt update\upgrade
Все параметры по умолчанию
`bash <(curl -fL https://raw.githubusercontent.com/AlexeyLCP/lucx-ui/main/install.sh)`

### Expected behavior

`
Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j2 KERNELRELEASE=5.15.0-194-generic -C /lib/modules/5.15.0-194-generic/build M=/var/lib/dkms/amneziawg/3c38e168beb7/build...(bad exit status: 2)
ERROR (dkms apport): binary package for amneziawg: 3c38e168beb7 not found
Error! Bad return status for module build on kernel: 5.15.0-194-generic (x86_64)
Consult /var/lib/dkms/amneziawg/3c38e168beb7/build/make.log for more information.
Ошибка сборки DKMS — текущий модуль не тронут.
--- /var/lib/dkms/amneziawg/3c38e168beb7/build/make.log (хвост) ---
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/xarray.h:14,
                 from ./include/linux/radix-tree.h:19,
                 from ./include/linux/fs.h:15,
                 from ./include/linux/highmem.h:5,
                 from ./include/linux/bvec.h:10,
                 from ./include/linux/skbuff.h:17,
                 from ./include/linux/ip.h:16,
                 from ./include/linux/if_tunnel.h:5,
                 from ./include/net/ip_tunnels.h:5,
                 from ./include/net/udp_tunnel.h:5,
                 from /var/lib/dkms/amneziawg/3c38e168beb7/build/compat/udp_tunnel/udp_tunnel_partial_compat.h:154,
                 from /var/lib/dkms/amneziawg/3c38e168beb7/build/compat/compat.h:70,
                 from <command-line>:
./include/linux/timer.h:186:12: note: previous declaration of ‘timer_delete’ with type ‘int(struct timer_list *)’
  186 | extern int timer_delete(struct timer_list *timer);
      |            ^~~~~~~~~~~~
In file included from <command-line>:
/var/lib/dkms/amneziawg/3c38e168beb7/build/compat/compat.h:1293:19: error: static declaration of ‘timer_delete’ follows non-static declaration
 1293 | static inline int timer_delete(struct timer_list *timer)
      |                   ^~~~~~~~~~~~
In file included from ./include/linux/workqueue.h:9,
                 from ./include/linux/srcu.h:21,
                 from ./include/linux/notifier.h:16,
                 from ./arch/x86/include/asm/uprobes.h:13,
                 from ./include/linux/uprobes.h:49,
                 from ./include/linux/mm_types.h:14,
                 from ./include/linux/mmzone.h:21,
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/xarray.h:14,
                 from ./include/linux/radix-tree.h:19,
                 from ./include/linux/fs.h:15,
                 from ./include/linux/highmem.h:5,
                 from ./include/linux/bvec.h:10,
                 from ./include/linux/skbuff.h:17,
                 from ./include/linux/ip.h:16,
                 from ./include/linux/if_tunnel.h:5,
                 from ./include/net/ip_tunnels.h:5,
                 from ./include/net/udp_tunnel.h:5,
                 from /var/lib/dkms/amneziawg/3c38e168beb7/build/compat/udp_tunnel/udp_tunnel_partial_compat.h:154,
                 from /var/lib/dkms/amneziawg/3c38e168beb7/build/compat/compat.h:70,
                 from <command-line>:
./include/linux/timer.h:186:12: note: previous declaration of ‘timer_delete’ with type ‘int(struct timer_list *)’
  186 | extern int timer_delete(struct timer_list *timer);
      |            ^~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/amneziawg/3c38e168beb7/build/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/amneziawg/3c38e168beb7/build/noise.o] Error 1
make: *** [Makefile:1928: /var/lib/dkms/amneziawg/3c38e168beb7/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.0-194-generic'
AWG install failed — AWG inbounds will be unavailable until manually fixed.
AWG: awg-quick not installed. AWG inbounds will not start.
Fix: x-ui install-awg
x-ui v3.8.5-lucx.265 installation finished, it is running now...
`

### Relevant logs

```shell
Sep 24 05:20:03 systemd[1]: Started x-ui Service.
Sep 24 05:20:03 x-ui[11890]: 2026/09/24 05:20:03 Starting x-ui 3.8.5-lucx.265
Sep 24 05:20:03 /usr/local/x-ui/x-ui[11890]: INFO - GC percent set to 75
Sep 24 05:20:03 /usr/local/x-ui/x-ui[11890]: INFO - Go memory soft limit not enforced: no explicit budget; soft limit left at Go default
Sep 24 05:20:03 /usr/local/x-ui/x-ui[11890]: INFO - Web server running HTTPS on [::]:34629
Sep 24 05:20:04 /usr/local/x-ui/x-ui[11890]: INFO - XRAY: infra/conf/serial: Reading config: &{Name:bin/config.json Format:json}
Sep 24 05:20:04 /usr/local/x-ui/x-ui[11890]: WARNING - XRAY: core: Xray 26.9.9 started
Sep 24 05:20:04 /usr/local/x-ui/x-ui[11890]: INFO - Sub server running HTTPS on [::]:2096
Sep 24 05:20:14 /usr/local/x-ui/x-ui[11890]: INFO - xray core supports the online-stats API; using connection-based onlines and access-log-free IP limit
Sep 24 05:24:07 x-ui[11890]: 2026/09/24 05:24:07 http: TLS handshake error from  us>
Sep 24 05:24:13 x-ui[11890]: 2026/09/24 05:24:13 http: TLS handshake error from  us>
```

### 3x-ui version

3.8.5-lucx.265 last

### How did you install 3x-ui?

install.sh script

### Operating system

Ubuntu 22.04 (Linux 5.15.0-194-generic)

### Is the panel behind a reverse proxy or CDN?

None

### Before submitting

- [x] I searched [existing issues](../issues?q=is%3Aissue) and this bug has not been reported.
- [x] I am running the latest released version of 3x-ui (or have verified the bug still exists on it).
- [x] This bug report is written in English.
- [x] I have redacted any sensitive data (tokens, real domains, client UUIDs).
